add_newline = false

format = "$directory$character"

[directory]
format = "\\($path\\) "
truncation_length = 2
truncate_to_repo = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
